lowercase: true
strip_punct: true
collapse_spaces: true

expand_abbr:
  mahalle: ["mah", "mah.", "mh", "mh.", "mahallesi"]
  cadde: ["cad", "cad.", "caddesi"]
  sokak: ["sok", "sok.", "sk", "sk."]
  bulvar: ["blv", "blv.", "bulv", "bulv."]
  daire: ["d", "daire"]
  no: ["no:", "numara"]
  kat: ["k.", "kat"]

canonical_map:
  cadde: "cadde"
  sokak: "sokak"
  mahalle: "mahalle"
  bulvar: "bulvar"
  no: "no"
  kat: "kat"
  daire: "daire"

remove_terms:
  - "apt"
  - "sitesi sitesi"
  - "turkiye cumhuriyeti devleti"
  - "tc"

parts:
  mahalle: "(?:mahalle|mah)\\s+([\\wçğıöşü]+)"
  cadde: "(?:cadde|cad)\\s+([\\wçğıöşü]+)"
  sokak: "(?:sokak|sk)\\s+([\\wçğıöşü]+)"
  no: "no\\s*:?\\s*(\\d+)"
  kat: "kat\\s*(\\d+)"
  daire: "(?:daire|d)\\s*(\\d+)"
